services:
  mysql:
    image: mysql:8.0
    container_name: sf-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf_selectrion
      MYSQL_USER: sf_root
      MYSQL_PASSWORD: lijiaxinga1.
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: lanstard/sf-server:latest
    build:
      context: ./server
    container_name: sf-server
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://sf_root:lijiaxinga1.@mysql:3306/sf_selectrion"
      SF_DATA_BASE_URL: "https://book.sfacg.com"
      SF_MB_BASE_URL: "https://m.sfacg.com"
      RUST_LOG: "actix_web=info"
    ports:
      - "8080:8080"

  client:
    image: lanstard/sf-client:latest
    build:
      context: ./clinet
      args:
        NEXT_PUBLIC_API_URL: http://127.0.0.1:8080
    container_name: sf-client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "3000:80"

volumes:
  mysql_data:
